version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - 9093:9093

  prometheus-msteams:
    image: quay.io/prometheusmsteams/prometheus-msteams
    container_name: prometheus-msteams
    environment:
      - TEAMS_REQUEST_URI=alertmanager
      - TEAMS_INCOMING_WEBHOOK_URL=https://thingtrax365.webhook.office.com/webhookb2/f6b51250-04e0-48fa-8e1c-29ddb78c6fef@90dd84a8-344f-42bd-bd3a-e7b371431fc2/IncomingWebhook/0fdd1a10d9f3457fbb64df83e5601396/48a1b375-728f-4d11-a474-f5291d5b5061
    restart: unless-stopped
    ports:
      - 2000:2000

  autorestart:
    image: vrathore/autorestart
    container_name: auto-restart
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: "${AUTOHEAL_CONTAINER_LABEL:-all}"
      AUTOHEAL_INTERVAL: "10"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: none

  should-keep-restarting:
    image: alpine
    container_name: alpine
    network_mode: none
    restart: "no"
    labels:
      - "$AUTOHEAL_CONTAINER_LABEL=true"
    healthcheck:
      test: exit 1
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 5s
    command: tail -f /dev/null