route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#alerts-client'
            api_url: 'https://hooks.slack.com/services/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'
