# route:
#     receiver: 'slack'

# receivers:
#     - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             text: "{{ .CommonAnnotations.description }}"
#             username: 'Prometheus'
#             channel: '#alerts-client'
#             api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: ['alertname']
  group_interval: 30s
  repeat_interval: 12h
  group_wait: 30s
  receiver: 'prometheus-msteams'

receivers:
- name: 'prometheus-msteams'
  webhook_configs: 
  - send_resolved: true
    url: 'http://prometheus-msteams:2000/alertmanager' 